#!/bin/bash 
if [[ $EUID -ne 0 ]]; then 
	echo "This script must be run as root" 1>&2 
	exit 1 
else 
	wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-3.6.5.tgz
	tar -xzvf mongodb-linux-x86_64-debian92-3.6.5.tgz
	cp -r mongodb-linux-x86_64-debian92-3.6.5/ /etc/
	rm -r mongodb-linux-x86_64-debian92-3.6.5/
	d=/etc/mongodb-linux-x86_64-debian92-3.6.5/bin/
	mkdir -p /data/db
	if [ -d "$d" ]; then
		echo 'export PATH=$PATH:/etc/mongodb-linux-x86_64-debian92-3.6.5/bin/' >>~/.bashrc
	else
		echo "Dir Wrong"
	fi
fi
echo -e "\e[44m\e[5mThank You for Using this tool...\e[0m"
