#!/bin/bash 
if [[ $EUID -ne 0 ]]; then 
	echo "This script must be run as root" 1>&2 
	exit 1 
else 
	git clone https://github.com/lwfinger/rtlwifi_new.git
	cd rtlwifi_new/
	make -j4
	make install
	sudo modprobe rtl8723be

fi
echo -e "\e[44m\e[5mThank You for Using this tool...\e[0m"
