#!/bin/bash

declare -r NUM1=5

num2=4

num3=$((NUM1+num2))
num4=$((NUM1-num2))
num5=$((NUM1*num2))
num6=$((NUM1/num2))
num7=$((NUM1**num2))
num8=$((NUM1%num2))

echo "$num3  $num4  $num5  $num6  $num7  $num8"

rand=5
let rand+=4
echo "$rand"

echo "rand++ = $(( rand++ ))"
echo "$rand"
echo "++rand = $(( ++rand ))"
echo "rand-- = $(( rand-- ))"
echo "--rand = $(( --rand ))"
