#!/bin/bash

file1="./test_file2"

if [ -e "$file1"	]; then
	echo "$file1 exists"
else
	touch $file1
	echo "$file1 Created"
fi

if [ -f "$file1" ]; then
	echo "$file1 is a normal file"
fi

# -e => file exists
# -f => Normal File
# -r => Readable File
# -w => Writable File
# -x => Executable File
# -d => Is a directory
# -L => Is a Symbolic Link
# -p => Named Pipe
# -S => Network Sock
# -G => Owned by the Group
# -O => Owned by the User
