#!/bin/bash

read -p "Enter two numbers to Sum: " num1 num2
sum=$((num1+num2))
echo "$num1 + $num2 = $sum"

read -sp "Enter the Secret Code: " secret
if [ "$secret" == "password" ]; then
	echo "Enter"
else
	echo "Wrong Password!!!"
fi
