#!/bin/bash

OIFS="$IFS"
IFS=","

read -p "Enter two numbers seprated by comma: " num1 num2

num1=${num1//[[:blank:]]/}
num2=${num2//[[:blank:]]/}

sum=$((num1+num2))
echo "$num1 + $num2 = $sum"

IFS="$OIFS"


name="Vipin"
echo "$name's toy"
echo "${name}'s toy"
